name: Docker
on:
  push:
    branches:
      - master
      # For testing docker building if needed
      - build/*

    tags:
      - v*

env:
  IMAGE_NAME: geras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          docker build --build-arg GERAS_VERSION=$VERSION --build-arg GIT_REVISION="$GITHUB_SHA" --build-arg GIT_BRANCH="$VERSION" --build-arg BUILD_USER="github-actions" -t image .

      - name: Sanity check image
        run: |
          exit=0
          docker run -t image || exit=$?
          if [[ $exit != 1 ]]; then
            echo "Expected 1 exit (usage), got $exit"
            exit 1
          fi
          
      # These need docker, so only run as part of the docker build process
      - name: Run integration tests
        run: |
          cd test && ./test-query.sh
